In [1]:
import torch
import torch.nn as nn

torch.manual_seed(4)

In [2]:
# Define your RNN
rnn = nn.RNN(input_size=1, hidden_size=2, num_layers=1, nonlinearity='relu', bias=False, batch_first=False)
total_params = sum(p.numel() for p in rnn.parameters())
print(f"- Number of parameters in the RNN: {total_params}\n")

# Set the weights for the first layer
rnn.weight_ih_l0.data = torch.tensor([[1.0],[2.0]])
rnn.weight_hh_l0.data = torch.tensor([[1.0, 0.0], [2.0, 0.0]])

input = torch.arange(1, 3).view(2, 1).float()

h0 = torch.tensor([[0.0, 0.0]])
output, hn = rnn(input, h0)

# print
print("- state weight:\n", rnn.all_weights)
print()
print("- output:\n", output)
print()
print("- last hidden:\n", hn)

- Number of parameters in the RNN: 6

- state weight:
 [[Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True), Parameter containing:
tensor([[1., 0.],
        [2., 0.]], requires_grad=True)]]

- output:
 tensor([[1., 2.],
        [3., 6.]], grad_fn=<SqueezeBackward1>)

- last hidden:
 tensor([[3., 6.]], grad_fn=<SqueezeBackward1>)


In [3]:
# Define your RNN
rnn = nn.RNN(input_size=1, hidden_size=2, num_layers=2, nonlinearity='relu', bias=False, batch_first=False)
total_params = sum(p.numel() for p in rnn.parameters())
print(f"- Number of parameters in the RNN: {total_params}\n")

# Set the weights for the first layer
rnn.weight_ih_l0.data = torch.tensor([[1.0],[2.0]])
rnn.weight_ih_l1.data = torch.tensor([[1.0, 0.0], [2.0, 1.0]])

rnn.weight_hh_l0.data = torch.tensor([[1.0, 0.0], [2.0, 0.0]])
rnn.weight_hh_l1.data = torch.tensor([[0.0, 0.0], [0.0, 1.0]])

input = torch.arange(1, 3).view(2, 1).float()

h0 = torch.tensor([[0.0, 0.0], [0.0, 0.0]])
output, hn = rnn(input, h0)

# print
print("- state weight:\n", rnn.all_weights[0])
print()
print("- hidden features weight:\n", rnn.all_weights[1])
print()
print("- output:\n", output)
print()
print("- last hidden:\n", hn)

- Number of parameters in the RNN: 14

- state weight:
 [Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True), Parameter containing:
tensor([[1., 0.],
        [2., 0.]], requires_grad=True)]

- hidden features weight:
 [Parameter containing:
tensor([[1., 0.],
        [2., 1.]], requires_grad=True), Parameter containing:
tensor([[0., 0.],
        [0., 1.]], requires_grad=True)]

- output:
 tensor([[ 1.,  4.],
        [ 3., 16.]], grad_fn=<SqueezeBackward1>)

- last hidden:
 tensor([[ 3.,  6.],
        [ 3., 16.]], grad_fn=<SqueezeBackward1>)


In [7]:
rnn = nn.RNN(input_size=1, hidden_size=1, num_layers=1, nonlinearity='relu', bias=True, batch_first=False)
total_params = sum(p.numel() for p in rnn.parameters())
print(f"- Number of parameters in the RNN: {total_params}\n")

rnn.weight_ih_l0.data = torch.tensor([[0.0]])
rnn.weight_hh_l0.data = torch.tensor([[1.0]])
rnn.bias_ih_l0.data   = torch.tensor([0.0])
rnn.bias_hh_l0.data   = torch.tensor([1.0])

input = torch.randn(10, 1)

h0 = torch.tensor([[0.0]])
output, hn = rnn(input, h0)

# print
print("- state weight:\n", rnn.all_weights)
print()
print("- output:\n", output)
print()
print("- last hidden:\n", hn)

- Number of parameters in the RNN: 4

- state weight:
 [[Parameter containing:
tensor([[0.]], requires_grad=True), Parameter containing:
tensor([[1.]], requires_grad=True), Parameter containing:
tensor([0.], requires_grad=True), Parameter containing:
tensor([1.], requires_grad=True)]]

- output:
 tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]], grad_fn=<SqueezeBackward1>)

- last hidden:
 tensor([[10.]], grad_fn=<SqueezeBackward1>)
